In [7]:
#Python List Manipulation Assignment

## a) Create a list named `fruits` containing the following items: "apple", "banana", "orange", "grape", "kiwi".
list = ["apple", "banana", "orange", "grape", "kiwi"]
list

['apple', 'banana', 'orange', 'grape', 'kiwi']

In [8]:
## b) Add "pear" to the end of the list
list.append("pear")
list

['apple', 'banana', 'orange', 'grape', 'kiwi', 'pear']

In [9]:
## c) Insert "mango" at the second position in the list.
list[1] = 'mango'
list

['apple', 'mango', 'orange', 'grape', 'kiwi', 'pear']

In [10]:
## d) Remove "orange" from the list.
list.pop(2)
list

['apple', 'mango', 'grape', 'kiwi', 'pear']

In [11]:
#Slicing and Indexing
## Slicing and Indexing
list_num = [0,1,2,3,4,5,6,7,8,9]
list_num

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
## b) Print the element at index 3.
list_num[3]


3

In [13]:
## c) Print a sublist containing the elements from index 2 to 6 (inclusive).
print(list_num[2:7])

[2, 3, 4, 5, 6]


In [14]:
## d) Print the last three elements using negative indexing
print(list_num[-1:-4:-1])

[9, 8, 7]


In [15]:
# List Comprehension
## a) Create a list named `squares` using a list comprehension that contains the squares of numbers from 1 to 10.
squares = [x ** 2 for x in range(1, 11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [16]:
## b) Create a new list named `even_squares` using a list comprehension that contains the squares of even numbers from the `squares` list.
even_squares = [x ** 2 for x in squares if x % 2 == 0 ]
print(even_squares)

[16, 256, 1296, 4096, 10000]


In [17]:
# List Manipulation
## a) Create a list named `colors` containing the following items: "red", "green", "blue", "yellow", "purple".
colors = ["red", "green", "blue", "yellow", "purple"]
colors

['red', 'green', 'blue', 'yellow', 'purple']

In [18]:
## b) Swap the first and last elements of the list.
colors[0], colors[-1] = colors[-1], colors[0]
colors

['purple', 'green', 'blue', 'yellow', 'red']

In [25]:
## c) Reverse the order of the list.
colors_a = colors[::-1]
print(colors_a)

['red', 'yellow', 'blue', 'green', 'purple']


In [26]:
## d) Remove the second and third elements from the list.
del colors_a[1:3]
print(colors_a)

['red', 'green', 'purple']


In [29]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [31]:
# b) Using slicing, create a new list `first_half` containing the first half of the `letters` list.
first_half = (letters[0:5])
print(first_half)

['a', 'b', 'c', 'd', 'e']


In [41]:
## c) Using slicing, create a new list `last_three` containing the last three elements of the `letters` list.
last_three = (letters[-3:])
print(last_three)

['h', 'i', 'j']


In [55]:
##  Nested Lists
# a) Create a nested list named `matrix` with the following rows:


In [58]:
import numpy as np


In [67]:
matrix = np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [70]:
## b) Print the element in the second row and third column.
element = matrix[1,2]
print(element)


6


In [71]:
## c) Use nested indexing to change the value at the second row and first column to 0.
matrix[1,0] = 0
print(matrix)

[[1 2 3]
 [0 5 6]
 [7 8 9]]
